name: Deploy to Albasidae Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout albasidae-fe repository
        uses: actions/checkout@v2
        with:
          repository: AlbaSidaeUOS/AlbaSidae-FE
          ref: main

      - name: Copy code to temporary folder
        run: |
          mkdir -p ../temp-frontend
          cp -r ./* ../temp-frontend/

      - name: Checkout albasidae repository
        uses: actions/checkout@v2
        with:
          repository: AlbaSidaeUOS/AlbaSidae
          token: ${{ secrets.GITHUB_TOKEN }}
          path: AlbaSidae

      - name: Copy files to albasidae/frontend
        run: |
          rm -rf AlbaSidae/frontend/*
          cp -r ../temp-frontend/* AlbaSidae/frontend/

      - name: Commit and push changes to albasidae/frontend
        run: |
          cd albasidae
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add frontend/*
          git commit -m "Deploy from albasidae-fe on push to main"
          git push origin main
