name: Deploy to Albasidae Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout albasidae-fe repository
        uses: actions/checkout@v3
        with:
          repository: AlbaSidaeUOS/AlbaSidae-FE
          ref: main

      - name: List files in albasidae-fe
        run: ls -al # albasidae-fe 레포지토리의 디렉토리 구조 확인

      - name: Copy code to temporary folder
        run: |
          mkdir -p ../temp-frontend
          cp -r ./* ../temp-frontend/

      - name: Checkout albasidae repository
        uses: actions/checkout@v3
        with:
          repository: AlbaSidaeUOS/AlbaSidae
          token: ${{ secrets.ALBASIDAE_PAT }}
          path: albasidae # 일관된 경로 사용

      - name: List files in root
        run: ls -al # 루트 디렉토리의 파일 구조 확인 (albasidae 폴더 확인)

      - name: List files in albasidae folder
        run: ls -al albasidae # albasidae 디렉토리 구조 확인

      - name: Copy files to albasidae/frontend
        run: |
          rm -rf albasidae/frontend/*
          cp -r ../temp-frontend/* albasidae/frontend/

      - name: Commit and push changes to albasidae/frontend
        run: |
          cd albasidae
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add frontend/*
          git commit -m "Deploy from albasidae-fe on push to main"
          git push origin main
